SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 2  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
SHOT_RADIUS = 3
SHOT_LIFETIME = 1
PLAYER_SHOOT_SPEED = 500
PLAYER_SPEED = 300
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_THRUST_POWER = 200
PLAYER_SHEILD_LIFETIME = 3
PLAYER_SHEILD_TIMEOUT = 9
